export const modalConstants = {
    SHOW_SEND_POST_MODAL: 'SHOW_SEND_POST_MODAL',
    CLOSE_SEND_POST_MODAL: 'CLOSE_SEND_POST_MODAL',
    SHOW_EDIT_POST_MODAL: 'SHOW_EDIT_POST_MODAL',
    CLOSE_EDIT_POST_MODAL: 'CLOSE_EDIT_POST_MODAL'
}